image: debian:buster-slim

stages:
  - build

variables:
  LINUX_HEADER_VERSION: "4.19.0-6"

.update: &update apt-get update -y && apt-get upgrade -y

kmod:
  stage: build
  before_script:
    - *update
    - apt-get install make gcc linux-headers-${LINUX_HEADER_VERSION}-amd64 -y --no-install-recommends
  script:
    - make KDIR=/lib/modules/${LINUX_HEADER_VERSION}-amd64/build

client:
  stage: build
  before_script:
    - *update
    - apt-get install make gcc libc6-dev linux-headers-${LINUX_HEADER_VERSION}-amd64 upx-ucl -y --no-install-recommends
  script:
    - make KDIR=/lib/modules/${LINUX_HEADER_VERSION}-amd64/build sc-client

format:
  stage: build
  before_script:
    - *update
    - apt-get install make clang-format git -y --no-install-recommends
  script:
    - make format
    - (! git status | grep modified:)

pages:
  stage: build
  before_script:
    - *update
    - apt-get install make python3-pip clang -y --no-install-recommends
    - pip3 install clang sphinx sphinx-rtd-theme hawkmoth
  script:
    - make -C doc html
    - mv doc/build/html/ public/
  artifacts:
    paths:
      - public
  only:
    - master
