image: debian:buster-slim

stages:
  - build

variables:
  LINUX_HEADER_VERSION: "4.19.0-6"

before_script:
  - apt update -y && apt upgrade -y

kmod:
  stage: build
  script:
    - apt install build-essential dkms linux-headers-${LINUX_HEADER_VERSION}-amd64 -y
    - make KDIR=/lib/modules/${LINUX_HEADER_VERSION}-amd64/build

client:
  stage: build
  script:
    - apt install build-essential dkms linux-headers-${LINUX_HEADER_VERSION}-amd64 -y
    - make KDIR=/lib/modules/${LINUX_HEADER_VERSION}-amd64/build sc-client

format:
  stage: build
  script:
    - apt install build-essential clang-format git -y
    - make format
    - (! git status | grep modified:)
