image: debian:buster-slim

stages:
  - build
  - test

variables:
  LINUX_HEADER_VERSION: "4.19.0-6"
  TEST_PATH: "/tmp/implant"
  CODECOV_TOKEN: ad5d0db4-a0a8-493f-8f9d-d0f66bd9e86d

.update: &update apt-get update -y && apt-get upgrade -y

.test:
  stage: test
  dependencies:
    - client
  before_script:
    - *update
    - apt-get install curl gcc ca-certificates -y --no-install-recommends
    - touch ${TEST_PATH}
  script:
    - sh client/${CI_JOB_NAME}.sh
  after_script:
    - sh <(curl -s https://codecov.io/bash -t ${CODECOV_TOKEN})

.test_with_valgrind:
  extends: .test
  before_script:
    - *update
    - apt-get install valgrind curl gcc ca-certificates -y --no-install-recommends
    - touch ${TEST_PATH}
  after_script:

kmod:
  stage: build
  before_script:
    - *update
    - apt-get install make gcc linux-headers-${LINUX_HEADER_VERSION}-amd64 -y --no-install-recommends
  script:
    - make KDIR=/lib/modules/${LINUX_HEADER_VERSION}-amd64/build

client:
  stage: build
  before_script:
    - *update
    - apt-get install make gcc libc6-dev linux-headers-${LINUX_HEADER_VERSION}-amd64 upx-ucl -y --no-install-recommends
  script:
    - make KDIR=/lib/modules/${LINUX_HEADER_VERSION}-amd64/build IMPLANT_DEVICE_PATH='\"${TEST_PATH}\"' COVERAGE=true PACKER=false DEBUG=true sc-client
  artifacts:
    paths:
      - sc-client
      - "*.gcno"

format:
  stage: build
  before_script:
    - *update
    - apt-get install make clang-format git -y --no-install-recommends
  script:
    - make format
    - (! git status | grep modified:)

pages:
  stage: build
  before_script:
    - *update
    - apt-get install make python3-pip clang -y --no-install-recommends
    - pip3 install clang sphinx sphinx-rtd-theme hawkmoth
  script:
    - make -C doc html
    - mv doc/build/html/ public/
  artifacts:
    paths:
      - public
  only:
    - master

### module tests: exec ###
test/exec/0/0:
  extends: .test
test/exec/0/1:
  extends: .test
test/exec/0/2:
  extends: .test
test/exec/0/3:
  extends: .test
test/exec/0/4:
  extends: .test
test/exec/0/5:
  extends: .test
test/exec/0/6:
  extends: .test
test/exec/0/7:
  extends: .test
test/exec/0/8:
  extends: .test
test/exec/0/9:
  extends: .test
test/exec/0/10:
  extends: .test
test/exec/0/11:
  extends: .test
test/exec/0/12:
  extends: .test
test/exec/0/13:
  extends: .test
test/exec/0/14:
  extends: .test
test/exec/0/15:
  extends: .test
test/exec/0/16:
  extends: .test
test/exec/0/17:
  extends: .test
test/exec/0/18:
  extends: .test
test/exec/0/19:
  extends: .test
test/exec/0/20:
  extends: .test
test/exec/0/21:
  extends: .test
test/exec/0/22:
  extends: .test
test/exec/0/23:
  extends: .test
test/exec/0/24:
  extends: .test
test/exec/0/25:
  extends: .test
test/exec/0/26:
  extends: .test
test/exec/0/27:
  extends: .test
test/exec/0/28:
  extends: .test
test/exec/0/29:
  extends: .test
test/exec/0/30:
  extends: .test
test/exec/0/31:
  extends: .test
test/exec/0/32:
  extends: .test
test/exec/0/33:
  extends: .test
test/exec/0/34:
  extends: .test
test/exec/0/35:
  extends: .test
test/exec/0/36:
  extends: .test
test/exec/0/37:
  extends: .test
test/exec/0/38:
  extends: .test
test/exec/0/39:
  extends: .test
test/exec/0/40:
  extends: .test
test/exec/0/41:
  extends: .test
test/exec/0/42:
  extends: .test
test/exec/0/43:
  extends: .test
test/exec/0/44:
  extends: .test
test/exec/0/45:
  extends: .test
test/exec/0/46:
  extends: .test
test/exec/0/47:
  extends: .test
test/exec/0/48:
  extends: .test
test/exec/0/49:
  extends: .test
test/exec/0/50:
  extends: .test
test/exec/0/51:
  extends: .test
test/exec/0/52:
  extends: .test
test/exec/0/53:
  extends: .test
test/exec/0/54:
  extends: .test
test/exec/0/55:
  extends: .test
test/exec/0/56:
  extends: .test
test/exec/0/57:
  extends: .test
test/exec/0/58:
  extends: .test
test/exec/0/59:
  extends: .test
test/exec/0/60:
  extends: .test
test/exec/0/61:
  extends: .test
test/exec/0/62:
  extends: .test
test/exec/0/63:
  extends: .test

test/exec/1/0:
  extends: .test_with_valgrind

### module tests: kill ###
test/kill/0/0:
  extends: .test

test/kill/1/0:
  extends: .test_with_valgrind

### module tests: hide ###
test/hide/0/0:
  extends: .test
test/hide/0/1:
  extends: .test

test/hide/1/0:
  extends: .test_with_valgrind
test/hide/1/1:
  extends: .test_with_valgrind

### module tests: unhide ###
test/unhide/0/0:
  extends: .test
test/unhide/0/1:
  extends: .test

test/unhide/1/0:
  extends: .test_with_valgrind
test/unhide/1/1:
  extends: .test_with_valgrind

### module tests: set ###
test/set/0/0:
  extends: .test
test/set/0/1:
  extends: .test
test/set/0/2:
  extends: .test
test/set/0/3:
  extends: .test

test/set/1/0:
  extends: .test_with_valgrind
test/set/1/1:
  extends: .test_with_valgrind
test/set/1/2:
  extends: .test_with_valgrind
test/set/1/3:
  extends: .test_with_valgrind

### module tests: unset ###
test/unset/0/0:
  extends: .test
test/unset/0/1:
  extends: .test
test/unset/0/2:
  extends: .test
test/unset/0/3:
  extends: .test

test/unset/1/0:
  extends: .test_with_valgrind
test/unset/1/1:
  extends: .test_with_valgrind
test/unset/1/2:
  extends: .test_with_valgrind
test/unset/1/3:
  extends: .test_with_valgrind

### module tests: help ###
test/help/0/0:
  extends: .test

test/help/1/0:
  extends: .test_with_valgrind
