image: debian:buster-slim

stages:
  - build
  - test

variables:
  LINUX_HEADER_VERSION: "4.19.0-6"
  TEST_PATH: "/tmp/implant"
  PROCESS_ID: "1"
  HELP_OUTPUT: "client/test/help.txt"

.update: &update apt-get update -y && apt-get upgrade -y

.test:
  stage: test
  dependencies:
    - client
  before_script:
    - *update
    - touch ${TEST_PATH}
  script:
    - bash client/${CI_JOB_NAME}.sh

kmod:
  stage: build
  before_script:
    - *update
    - apt-get install make gcc linux-headers-${LINUX_HEADER_VERSION}-amd64 -y --no-install-recommends
  script:
    - make KDIR=/lib/modules/${LINUX_HEADER_VERSION}-amd64/build

client:
  stage: build
  before_script:
    - *update
    - apt-get install make gcc libc6-dev linux-headers-${LINUX_HEADER_VERSION}-amd64 upx-ucl -y --no-install-recommends
  script:
    - make KDIR=/lib/modules/${LINUX_HEADER_VERSION}-amd64/build IMPLANT_DEVICE_PATH='\"${TEST_PATH}\"' sc-client
  artifacts:
    paths:
      - sc-client

format:
  stage: build
  before_script:
    - *update
    - apt-get install make clang-format git -y --no-install-recommends
  script:
    - make format
    - (! git status | grep modified:)

pages:
  stage: build
  before_script:
    - *update
    - apt-get install make python3-pip clang -y --no-install-recommends
    - pip3 install clang sphinx sphinx-rtd-theme hawkmoth
  script:
    - make -C doc html
    - mv doc/build/html/ public/
  artifacts:
    paths:
      - public
  only:
    - master

### module tests: exec ###
test/exec/0/0:
  extends: .test
test/exec/0/1:
  extends: .test
test/exec/0/2:
  extends: .test

### module tests: kill ###
test/kill/0/0:
  extends: .test

### module tests: hide ###
test/hide/0/0:
  extends: .test
test/hide/0/1:
  extends: .test

### module tests: unhide ###
test/unhide/0/0:
  extends: .test
test/unhide/0/1:
  extends: .test

### module tests: set ###
test/set/0/0:
  extends: .test
test/set/0/1:
  extends: .test
test/set/0/2:
  extends: .test
test/set/0/3:
  extends: .test

### module tests: unset ###
test/unset/0/0:
  extends: .test
test/unset/0/1:
  extends: .test
test/unset/0/2:
  extends: .test
test/unset/0/3:
  extends: .test

### module tests: help ###
test/help/0/0:
  extends: .test
